### ISSUE TITLE
[Suggestion] Favorites and/or list currently installed videos in-app

### ISSUE THREAD

**Issue by ArchOwlen** [CapitaineJSparrow/steam-repo-manager#10]
Currently we can just download videos
It would be neat if it said "installed" or gave us a list of installed videos without having to check the folder

Also being able to favorite videos to remove videos and add them again at a later time

**Comment by CapitaineJSparrow** [comment]
I know it has been a while but since version [1.10 released today](https://flathub.org/apps/details/com.steamdeckrepo.manager) The software is now following steam OS installation path, allowing to install multiple video at once and steam OS will pick one randomly at boot. When a video is installed, the "download" button is disabled so you know which video is installed
